"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "allow-cancel-operation"
description = "Enables the cancel_operation command without any pre-configured scope."
commands.allow = ["cancel_operation"]

[[permission]]
identifier = "deny-cancel-operation"
description = "Denies the cancel_operation command without any pre-configured scope."
commands.deny = ["cancel_operation"]
